<a href="https://colab.research.google.com/github/JakubPac/kurs_data_science/blob/main/keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import plotly.express as px

In [4]:
from tensorflow.keras.models import Sequential

In [6]:
model = Sequential()
print(model)

<Sequential name=sequential_1, built=False>

In [7]:
from tensorflow.keras.layers import Dense

In [9]:
model.add(Dense(units = 4, input_shape = (10,)))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [10]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 4)              │            44 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 44 (176.00 B)

 Trainable params: 44 (176.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.add(Dense(units = 2))

In [12]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 4)              │            44 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 2)              │            10 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 54 (216.00 B)

 Trainable params: 54 (216.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
from tensorflow.keras.activations import linear
randomdata = np.linspace(-3, 3, 300)
data = pd.DataFrame({'data': randomdata, 'linear' : linear(randomdata)})
data.head()

       data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [14]:
px.line(data, x = 'data', y = 'linear', width = 500, height = 400, range_y=[-3,3])

In [15]:
from tensorflow.keras.activations import sigmoid
randomdata = np.linspace(-3, 3, 300)
data = pd.DataFrame({'data': randomdata, 'sigmoid' : sigmoid(randomdata)})
data.head()

       data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [19]:
px.line(data, x = 'data', y = 'sigmoid', width = 500, height = 400, range_y=[-0.5,1.5])

In [20]:
from tensorflow.keras.activations import relu
randomdata = np.linspace(-3, 3, 300)
data = pd.DataFrame({'data': randomdata, 'relu' : relu(randomdata)})
data.head()

       data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [22]:
px.line(data, x = 'data', y = 'relu', width = 500, height = 400, range_y=[-0.5,3])

In [23]:
from tensorflow.keras.activations import tanh
randomdata = np.linspace(-3, 3, 300)
data = pd.DataFrame({'data': randomdata, 'tanh' : tanh(randomdata)})
data.head()

       data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [24]:
px.line(data, x = 'data', y = 'tanh', width = 500, height = 400, range_y=[-1,1])

In [25]:
model = Sequential()
model.add(Dense(units = 8, activation = 'relu', input_shape = (10,)))
model.add(Dense(units = 1, activation = 'sigmoid'))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# klasyfikacja binarna
model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

# klsyfikacja wieloklasowa
model.compile(optimizer = 'rmsprop',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])

#regresja
model.compile(optimizer = 'rmsprop',
              loss = 'mse')

klasyfikacja binarna

In [26]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size = (10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)

In [27]:
data[:3]

array([[-1.24620291e+00,  1.72779935e+00,  4.96129784e-01,
        -1.95591419e+00,  4.32608466e-01,  3.69519934e-02,
         5.37279026e-01, -2.40334171e-01,  1.45011025e+00,
        -1.10422133e-01, -3.81068467e-01, -1.73644303e+00,
        -1.35700892e+00, -1.21784741e+00, -6.33806336e-01,
        -5.62572672e-01, -5.37926442e-01,  7.97521733e-01,
        -2.97921786e-01,  1.14635308e+00,  2.82387783e-01,
        -2.16688270e-01, -8.68600615e-01, -1.35553978e-01,
         3.05423515e+00,  6.47917858e-01,  1.05939057e+00,
        -3.51054655e-01,  1.20171506e+00,  5.74785375e-01,
         6.33222548e-01, -4.39585803e-01, -1.73561043e+00,
        -7.85594306e-01, -1.51346479e+00,  5.90346452e-01,
         1.12098436e+00,  4.12082377e-01, -5.19049487e-01,
         7.92014810e-01, -4.14520721e-01, -2.81048916e-01,
         3.44105063e-02,  1.36662700e+00, -5.98366139e-01,
         1.01072115e+00, -1.13531790e+00,  2.68722319e-01,
        -1.02621558e-01, -1.83441171e-01,  6.83276275e-01,
         3.62740786e-01, -7.69860336e-01, -1.40726011e+00,
        -4.14503100e-01, -1.99956350e+00, -1.97545108e-01,
        -1.86646242e+00,  2.57470517e-01, -6.38457421e-01,
        -7.77437557e-02,  3.74588871e-01,  6.21823259e-02,
        -6.35234635e-01, -9.22378031e-02,  6.21649445e-01,
        -8.32296272e-01,  1.76088462e+00,  1.15279857e-01,
        -6.26601832e-01,  2.99106636e-01,  2.66324699e-01,
         8.39850324e-01, -2.10532723e+00, -1.52457005e-01,
         5.35957494e-01, -1.19770659e+00, -2.45311807e-01,
         1.08422597e+00,  6.83696716e-02, -1.77831883e+00,
         1.56779046e-01, -5.36436111e-01, -8.41662910e-01,
         7.77175927e-01, -2.49996528e-01, -1.44513316e+00,
         2.06357605e-01,  1.11630863e+00, -1.32389321e-01,
         3.31790744e-01,  1.23595629e+00,  4.18865541e-01,
         1.84224628e-01, -1.99086425e-01, -1.39730157e+00,
         1.19138765e+00,  1.58600373e+00, -8.38846868e-01,
         1.05996716e+00,  7.02581835e-01,  1.24820018e+00,
        -5.92997865e-01,  1.02499169e-01, -1.42334298e+00,
         1.74261868e+00,  2.33745464e+00,  9.17070131e-01,
        -7.71477902e-01,  2.56648537e-01, -8.59733751e-01,
        -8.18020464e-01,  1.49988797e+00,  5.87107526e-01,
         1.00788351e+00, -2.33426537e-01, -8.18890943e-01,
         1.08693949e+00,  2.33002510e-01,  1.25500432e+00,
         8.19501959e-01,  8.50918476e-01,  7.76021021e-01,
        -6.27927111e-01, -2.52541139e-01, -1.54345742e+00,
        -4.13887397e-01, -1.14113694e+00,  1.03431908e+00,
         3.87228673e-01, -3.41609605e-02,  1.29829209e+00,
        -2.77884691e-01, -6.24265746e-01, -9.49537046e-01,
         7.45747832e-01, -1.82978714e+00, -8.67000723e-01,
         8.62800072e-01, -8.84064956e-01,  5.29788104e-01,
         1.25634457e-01, -1.45250664e+00,  1.48016886e+00,
         3.81964358e-01, -1.49230389e+00, -1.21961303e+00,
        -4.33569971e-01,  5.04194314e-01,  6.72052380e-01],
       [-7.02798948e-01,  1.51812906e-03, -8.31550784e-01,
        -7.25674978e-01,  3.58772555e-01,  4.46371766e-01,
         2.69757324e-01, -9.06560689e-01, -3.76370650e-01,
        -9.72310197e-01,  3.75541620e-01,  6.89482045e-01,
        -3.03519021e-01, -6.42307273e-01, -6.51818279e-01,
        -1.80649232e+00, -1.56612812e+00, -1.23042712e+00,
        -9.63830394e-01, -9.67977319e-01, -1.95652973e-01,
         9.11791987e-01,  4.98729221e-01,  2.05742714e-02,
         1.29314431e+00,  6.55827743e-01,  1.86409685e-02,
        -4.89042221e-01,  6.73423886e-01,  4.58646920e-01,
         2.15028778e-01, -3.16433232e-02, -5.23007419e-01,
        -3.20151570e-01, -6.42077565e-01,  1.40094175e+00,
         4.66237307e-01, -8.03843275e-01,  1.75168463e+00,
         5.78564886e-01,  1.05725124e+00, -4.24612802e-01,
        -3.79879913e-02,  6.64119277e-03,  7.14019486e-01,
        -1.23147917e-01,  4.56470837e-02, -7.32125044e-01,
        -7.72201457e-01, -6.04705743e-01,  9.11456049e-01,
        -2.05295099e+00,  7.97525870e-01, -6.16635818e-01,
        -9.74580921e-01, -8.17579758e-02, -1.39365847e-02,
         1.17691132e+00, -1.35212443e-01,  8.61333840e-01,
         1.00831587e+00, -1.67429104e+00,  1.21327706e+00,
         1.89302740e+00, -8.55787234e-01, -1.57755216e-02,
        -5.03726325e-01,  5.37387085e-01, -1.51386521e-01,
        -2.96436819e-01, -7.66337486e-01, -8.23704183e-01,
        -1.47764795e+00, -5.29507045e-01,  1.10876310e+00,
         5.12696829e-01,  5.05432868e-01, -3.07077596e-01,
         5.21460678e-01,  4.06619237e-02, -5.62201228e-01,
        -6.51391196e-01, -1.05847147e+00, -1.20443526e+00,
         3.37156652e-01, -3.97970517e-01, -3.13235286e-01,
        -1.53907258e+00,  7.18203101e-01,  3.54640016e-01,
        -2.02362798e-01, -9.27367687e-01, -1.42497569e+00,
         1.16079892e-01, -2.34573883e+00,  1.13712028e-01,
         4.76705565e-01, -1.70843732e+00, -5.76948790e-01,
        -4.85160814e-01,  2.80116925e-01,  1.07623683e+00,
         1.61561072e+00,  5.83033334e-01, -7.40511146e-01,
        -7.10310878e-01,  1.99418028e+00, -1.78551599e+00,
         1.81400258e+00, -7.57607433e-01, -7.38805793e-01,
        -4.15491141e-01,  5.63212373e-02,  7.95011013e-01,
         9.51495493e-01, -3.52925354e-01,  1.33003414e+00,
         2.56192069e-03, -6.82272890e-02,  1.21303736e+00,
         1.00041078e-01, -2.21896759e+00,  1.62156260e+00,
        -1.67604198e+00,  2.76494407e-02, -1.15321263e+00,
        -9.46002262e-02, -1.26271342e+00,  4.17393208e-01,
         9.76438431e-02, -1.29419418e+00, -3.01850482e-01,
        -9.19740244e-01, -1.15127341e+00,  8.64098030e-01,
        -3.58861623e-01, -9.50018993e-01,  1.54170267e+00,
         4.02012245e-01,  9.61602932e-01, -2.91028711e-01,
         6.90690880e-01, -6.01601034e-01,  1.80164892e-01,
         1.27590940e+00,  8.63756088e-02,  9.30013802e-01,
        -1.01152398e+00, -6.31337715e-01,  6.84983799e-01],
       [ 3.49582556e-01,  3.80345708e-01,  6.36327826e-01,
        -7.06996754e-01,  9.09542067e-01,  1.65502602e+00,
        -1.07601387e+00,  2.77592620e-01,  1.22462075e-01,
         9.67284174e-01,  2.13654274e-01, -1.99222278e+00,
        -7.49665773e-01, -1.71617045e-01,  1.14318613e+00,
        -3.25367447e-01,  1.56166863e+00, -3.06619288e-01,
         1.01523066e+00,  1.29359175e+00,  2.32343017e+00,
         1.32712481e+00,  2.28791599e-01, -7.99213201e-01,
         3.99620163e-01, -8.20586920e-01,  1.23924399e-01,
         5.25321755e-01,  2.26705249e-01,  2.64568467e-01,
         1.18958728e+00, -5.59542815e-01,  6.29769995e-01,
         9.28049422e-01, -4.71057343e-01,  1.28114263e+00,
         1.63895514e-01,  8.34435817e-02,  1.23965261e+00,
         8.55630553e-01,  3.65828858e-01, -4.31670615e-02,
         5.12169108e-01,  3.56899231e-01,  9.54377355e-01,
         4.42954531e-01,  3.62037099e-01,  3.32372133e-01,
        -1.26595456e+00,  5.08505150e-01,  3.52707999e-01,
        -6.01830319e-01,  2.46307381e+00,  1.33508396e+00,
        -6.40587306e-01,  1.33665515e+00, -4.39762442e-02,
        -1.58916178e-02, -1.87669378e+00,  1.07439254e-01,
         1.08190178e-01, -5.88243937e-01,  7.01892034e-01,
         1.14456281e+00,  1.36072217e+00,  1.06412411e-01,
         6.28369213e-01, -2.89078242e-01, -1.04463597e+00,
         3.46112966e-01,  1.87382837e+00, -6.07524847e-01,
        -4.61412065e-04,  9.57857992e-01, -6.89934081e-01,
        -4.13207085e-01, -1.46965806e+00, -8.30455112e-01,
         1.21827944e+00, -2.67030291e-01,  1.25941493e+00,
        -3.92394040e-01,  5.20778385e-01, -1.51017800e+00,
         9.15547680e-01,  3.38845392e-01, -1.47097899e+00,
         6.53142472e-01,  1.34116519e+00, -1.28244951e+00,
         1.93870060e+00,  1.21185467e+00, -3.86846296e-01,
         4.60564455e-01,  1.78465517e-01,  7.09711501e-03,
         1.62365947e+00, -1.05608450e+00,  7.54314288e-01,
         1.40180201e+00, -1.67015028e-01,  8.40921577e-01,
        -2.82450382e-01,  6.34139598e-01, -1.59331560e-01,
         1.33411768e+00, -1.19738814e+00, -5.68213081e-01,
         3.80783398e-01, -8.17888999e-01,  1.00750710e+00,
        -2.89827384e-01, -1.22214328e+00, -1.07755182e+00,
         8.84994299e-02, -2.20791148e-01,  1.52173166e-01,
         9.57726266e-01, -1.94745330e+00, -1.00409803e+00,
        -5.67204553e-01,  1.45813586e-01, -1.14128660e+00,
        -1.07267473e-01, -4.76297554e-01,  2.95412733e-01,
        -3.61479916e-01, -1.00080417e+00, -6.09945405e-01,
        -4.61524553e-01,  1.10519513e+00, -3.49146807e-01,
        -1.37925127e+00,  1.38766499e-01, -1.15625832e+00,
        -2.48909817e-01,  1.52447072e+00, -5.43206535e-01,
         4.96137050e-01, -7.13222329e-01, -8.75256236e-01,
        -1.25975944e+00,  1.26641321e+00,  7.10553086e-01,
         7.88478981e-01, -8.94003739e-01,  4.24987331e-02,
        -2.21615974e-01,  8.32339499e-01,  1.66228047e+00]])

In [28]:
labels[:10]

array([[0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [29]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(units = 1, activation = 'sigmoid'))

model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

model.fit(data, labels, epochs = 20)

Epoch 1/20

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.4941 - loss: 0.7819
Epoch 2/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5520 - loss: 0.6917
Epoch 3/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5803 - loss: 0.6739
Epoch 4/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6145 - loss: 0.6567
Epoch 5/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6318 - loss: 0.6438
Epoch 6/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6524 - loss: 0.6300
Epoch 7/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6667 - loss: 0.6177
Epoch 8/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6906 - loss: 0.5989
Epoch 9/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7047 - loss: 0.5840
Epoch 10/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7124 - loss: 0.5733
Epoch 11/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7328 - loss: 0.5569
Epoch 12/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7340 - loss: 0.5454
Epoch 13/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7334 - loss: 0.5400
Epoch 14/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7498 - loss: 0.5207
Epoch 15/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7536 - loss: 0.5135
Epoch 16/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7692 - loss: 0.4977
Epoch 17/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7673 - loss: 0.4955
Epoch 18/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7779 - loss: 0.4813
Epoch 19/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7841 - loss: 0.4702
Epoch 20/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7868 - loss: 0.4660

In [30]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(units = 1, activation = 'sigmoid'))

model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

model.fit(data, labels, epochs = 20, batch_size = 30)

Epoch 1/20

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4939 - loss: 0.7593
Epoch 2/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5497 - loss: 0.6910
Epoch 3/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5801 - loss: 0.6738
Epoch 4/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6213 - loss: 0.6559
Epoch 5/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6247 - loss: 0.6479
Epoch 6/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6544 - loss: 0.6293
Epoch 7/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6736 - loss: 0.6188
Epoch 8/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6960 - loss: 0.5969
Epoch 9/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7054 - loss: 0.5806
Epoch 10/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7180 - loss: 0.5713
Epoch 11/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7365 - loss: 0.5491
Epoch 12/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7371 - loss: 0.5402
Epoch 13/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7469 - loss: 0.5253
Epoch 14/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7577 - loss: 0.5159
Epoch 15/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7613 - loss: 0.5041
Epoch 16/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7637 - loss: 0.4979
Epoch 17/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7676 - loss: 0.4908
Epoch 18/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7829 - loss: 0.4740
Epoch 19/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7837 - loss: 0.4674
Epoch 20/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7885 - loss: 0.4594

In [31]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(units = 1, activation = 'sigmoid'))

model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

model.fit(data, labels, epochs = 20, batch_size = 32, validation_split=0.2)

Epoch 1/20

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5119 - loss: 0.7758 - val_accuracy: 0.5265 - val_loss: 0.7114
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5517 - loss: 0.6945 - val_accuracy: 0.5130 - val_loss: 0.7096
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5849 - loss: 0.6740 - val_accuracy: 0.5170 - val_loss: 0.7114
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6114 - loss: 0.6552 - val_accuracy: 0.5195 - val_loss: 0.7129
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6300 - loss: 0.6437 - val_accuracy: 0.5070 - val_loss: 0.7190
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6539 - loss: 0.6275 - val_accuracy: 0.5065 - val_loss: 0.7260
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6793 - loss: 0.6080 - val_accuracy: 0.5100 - val_loss: 0.7307
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6893 - loss: 0.5971 - val_accuracy: 0.5075 - val_loss: 0.7402
Epoch 9/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7086 - loss: 0.5791 - val_accuracy: 0.5105 - val_loss: 0.7488
Epoch 10/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7220 - loss: 0.5641 - val_accuracy: 0.5015 - val_loss: 0.7650
Epoch 11/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7312 - loss: 0.5494 - val_accuracy: 0.5105 - val_loss: 0.7785
Epoch 12/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7515 - loss: 0.5305 - val_accuracy: 0.5095 - val_loss: 0.7870
Epoch 13/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7575 - loss: 0.5173 - val_accuracy: 0.5065 - val_loss: 0.8041
Epoch 14/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7619 - loss: 0.5095 - val_accuracy: 0.5090 - val_loss: 0.8182
Epoch 15/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7697 - loss: 0.4931 - val_accuracy: 0.5020 - val_loss: 0.8365
Epoch 16/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7835 - loss: 0.4759 - val_accuracy: 0.5035 - val_loss: 0.8554
Epoch 17/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7856 - loss: 0.4669 - val_accuracy: 0.5085 - val_loss: 0.8726
Epoch 18/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7891 - loss: 0.4562 - val_accuracy: 0.5080 - val_loss: 0.8857
Epoch 19/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8029 - loss: 0.4399 - val_accuracy: 0.5115 - val_loss: 0.9051
Epoch 20/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8083 - loss: 0.4363 - val_accuracy: 0.5110 - val_loss: 0.9287

In [33]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(units = 1, activation = 'sigmoid'))

model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

history = model.fit(data, labels, epochs = 20, batch_size = 32, validation_split=0.2, verbose = 0)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

In [34]:
metrics = history.history
metrics.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [35]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(units = 1, activation = 'sigmoid'))

model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

history = model.fit(data, labels, epochs = 20, batch_size = 32, validation_split=0.2, verbose = 1)

Epoch 1/20

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5046 - loss: 0.7807 - val_accuracy: 0.5250 - val_loss: 0.7097
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5453 - loss: 0.6920 - val_accuracy: 0.5305 - val_loss: 0.7043
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5998 - loss: 0.6653 - val_accuracy: 0.5240 - val_loss: 0.7080
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6154 - loss: 0.6519 - val_accuracy: 0.5230 - val_loss: 0.7080
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6445 - loss: 0.6374 - val_accuracy: 0.5260 - val_loss: 0.7132
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6639 - loss: 0.6241 - val_accuracy: 0.5275 - val_loss: 0.7146
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6895 - loss: 0.6039 - val_accuracy: 0.5245 - val_loss: 0.7206
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7012 - loss: 0.5945 - val_accuracy: 0.5225 - val_loss: 0.7327
Epoch 9/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7187 - loss: 0.5758 - val_accuracy: 0.5190 - val_loss: 0.7364
Epoch 10/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7346 - loss: 0.5544 - val_accuracy: 0.5330 - val_loss: 0.7455
Epoch 11/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7465 - loss: 0.5393 - val_accuracy: 0.5280 - val_loss: 0.7565
Epoch 12/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7676 - loss: 0.5234 - val_accuracy: 0.5220 - val_loss: 0.7726
Epoch 13/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7710 - loss: 0.5114 - val_accuracy: 0.5260 - val_loss: 0.7809
Epoch 14/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7795 - loss: 0.4985 - val_accuracy: 0.5325 - val_loss: 0.7923
Epoch 15/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7878 - loss: 0.4849 - val_accuracy: 0.5225 - val_loss: 0.8112
Epoch 16/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7873 - loss: 0.4780 - val_accuracy: 0.5200 - val_loss: 0.8279
Epoch 17/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8005 - loss: 0.4584 - val_accuracy: 0.5290 - val_loss: 0.8405
Epoch 18/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8044 - loss: 0.4559 - val_accuracy: 0.5180 - val_loss: 0.8629
Epoch 19/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8072 - loss: 0.4474 - val_accuracy: 0.5180 - val_loss: 0.8732
Epoch 20/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8076 - loss: 0.4403 - val_accuracy: 0.5165 - val_loss: 0.8940

In [36]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2,size = (5,1))

In [38]:
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

array([[0.26470143],
       [0.24423255],
       [0.36654177],
       [0.13411283],
       [0.30931622]], dtype=float32)

In [39]:
np.argmax(model.predict(test_data), axis = 1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step

array([0, 0, 0, 0, 0])

klasyfikacja wieloklasowa

In [41]:
data = np.random.randn(10000, 150)
labels = np.random.randint(10, size = (10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)

In [42]:
labels[:10]

array([[4],
       [1],
       [1],
       [4],
       [5],
       [1],
       [7],
       [7],
       [5],
       [4]])

In [44]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [45]:
labels[1]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(units = 10, activation = 'softmax'))

model.compile(optimizer = 'rmsprop',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])

model.fit(data, labels, epochs = 30, batch_size = 32, validation_split=0.2)

Epoch 1/30

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0897 - loss: 2.6259 - val_accuracy: 0.0985 - val_loss: 2.4511
Epoch 2/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1177 - loss: 2.3623 - val_accuracy: 0.1010 - val_loss: 2.4000
Epoch 3/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.1396 - loss: 2.2780 - val_accuracy: 0.1055 - val_loss: 2.3876
Epoch 4/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.1784 - loss: 2.2285 - val_accuracy: 0.0970 - val_loss: 2.3870
Epoch 5/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1947 - loss: 2.1955 - val_accuracy: 0.0930 - val_loss: 2.3973
Epoch 6/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2174 - loss: 2.1713 - val_accuracy: 0.0940 - val_loss: 2.4078
Epoch 7/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2318 - loss: 2.1488 - val_accuracy: 0.0920 - val_loss: 2.4166
Epoch 8/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2385 - loss: 2.1296 - val_accuracy: 0.0920 - val_loss: 2.4288
Epoch 9/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2446 - loss: 2.1137 - val_accuracy: 0.0930 - val_loss: 2.4430
Epoch 10/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2604 - loss: 2.0914 - val_accuracy: 0.1005 - val_loss: 2.4571
Epoch 11/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2569 - loss: 2.0845 - val_accuracy: 0.0995 - val_loss: 2.4703
Epoch 12/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2705 - loss: 2.0715 - val_accuracy: 0.0975 - val_loss: 2.4848
Epoch 13/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2684 - loss: 2.0631 - val_accuracy: 0.0985 - val_loss: 2.5016
Epoch 14/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2912 - loss: 2.0310 - val_accuracy: 0.0995 - val_loss: 2.5143
Epoch 15/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2864 - loss: 2.0223 - val_accuracy: 0.1005 - val_loss: 2.5301
Epoch 16/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2851 - loss: 2.0166 - val_accuracy: 0.1010 - val_loss: 2.5455
Epoch 17/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2933 - loss: 2.0058 - val_accuracy: 0.0980 - val_loss: 2.5606
Epoch 18/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3020 - loss: 1.9869 - val_accuracy: 0.0980 - val_loss: 2.5787
Epoch 19/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3147 - loss: 1.9713 - val_accuracy: 0.0990 - val_loss: 2.5887
Epoch 20/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.3003 - loss: 1.9755 - val_accuracy: 0.0995 - val_loss: 2.6039
Epoch 21/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.3114 - loss: 1.9651 - val_accuracy: 0.0945 - val_loss: 2.6163
Epoch 22/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.3139 - loss: 1.9608 - val_accuracy: 0.1005 - val_loss: 2.6285
Epoch 23/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3138 - loss: 1.9590 - val_accuracy: 0.1020 - val_loss: 2.6419
Epoch 24/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3230 - loss: 1.9435 - val_accuracy: 0.0985 - val_loss: 2.6539
Epoch 25/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3258 - loss: 1.9249 - val_accuracy: 0.0990 - val_loss: 2.6670
Epoch 26/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3222 - loss: 1.9315 - val_accuracy: 0.1030 - val_loss: 2.6800
Epoch 27/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3178 - loss: 1.9275 - val_accuracy: 0.0995 - val_loss: 2.6904
Epoch 28/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3324 - loss: 1.9209 - val_accuracy: 0.0995 - val_loss: 2.7043
Epoch 29/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3282 - loss: 1.9196 - val_accuracy: 0.1040 - val_loss: 2.7168
Epoch 30/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3459 - loss: 1.8928 - val_accuracy: 0.0955 - val_loss: 2.7272

In [47]:
test_data = np.random.random((10,150))
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step

array([[0.06166071, 0.06882022, 0.01399922, 0.19210012, 0.15145351,
        0.11566465, 0.09562697, 0.12694946, 0.08786162, 0.08586358],
       [0.06281079, 0.11401916, 0.04773058, 0.07924359, 0.12011567,
        0.18986985, 0.11853279, 0.07462616, 0.10182176, 0.09122965],
       [0.10255731, 0.09861618, 0.02466171, 0.08192348, 0.14088075,
        0.17868355, 0.11103883, 0.08238949, 0.07303834, 0.10621033],
       [0.04197709, 0.09051337, 0.01994624, 0.15632199, 0.24348484,
        0.15674853, 0.08018827, 0.05531607, 0.0754423 , 0.08006127],
       [0.03566093, 0.03632363, 0.01783173, 0.12469154, 0.197579  ,
        0.15456222, 0.06859366, 0.08009425, 0.20042406, 0.08423904],
       [0.05196027, 0.13196288, 0.04652081, 0.16467424, 0.21312018,
        0.05766203, 0.04789284, 0.09325808, 0.11099226, 0.0819565 ],
       [0.07997294, 0.10124237, 0.02988112, 0.13500276, 0.16430554,
        0.11524425, 0.13192931, 0.11595891, 0.07545957, 0.05100314],
       [0.03726402, 0.07814331, 0.01321357, 0.10621636, 0.10801319,
        0.25999746, 0.10208508, 0.14814793, 0.08862025, 0.05829884],
       [0.03994427, 0.07926204, 0.01620149, 0.12315223, 0.20878015,
        0.14012139, 0.06679466, 0.1266758 , 0.11733641, 0.08173153],
       [0.05888028, 0.09947073, 0.04733925, 0.07243871, 0.27550393,
        0.14014153, 0.09088574, 0.05959327, 0.09685443, 0.05889216]],
      dtype=float32)

In [48]:
np.argmax(model.predict(test_data), axis = 1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step

array([3, 5, 5, 4, 8, 4, 4, 5, 4, 4])

regresja

In [49]:
data =- np.random.random((10000,150))
labels = 50 * np.random.random(10000)

In [51]:
labels[:10]

array([29.80322026, 21.0147986 , 43.26422963, 45.51572945,  4.13604719,
       23.37906621, 19.5898036 , 48.12161824,  4.63944158, 26.04825137])

In [52]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(units = 1))

model.compile(optimizer = 'rmsprop',
              loss = 'mse')

model.fit(data, labels, epochs = 30, batch_size = 32, validation_split = 0.2)

Epoch 1/30

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 447.3857 - val_loss: 205.2684
Epoch 2/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 208.8040 - val_loss: 205.0000
Epoch 3/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 212.5366 - val_loss: 207.3446
Epoch 4/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 211.5423 - val_loss: 205.2678
Epoch 5/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 206.9678 - val_loss: 205.3187
Epoch 6/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 215.4391 - val_loss: 205.5903
Epoch 7/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 207.3190 - val_loss: 206.3992
Epoch 8/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 210.6007 - val_loss: 207.6519
Epoch 9/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 211.0095 - val_loss: 205.9747
Epoch 10/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 211.3549 - val_loss: 206.0307
Epoch 11/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 212.8340 - val_loss: 206.8266
Epoch 12/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 211.3247 - val_loss: 206.8236
Epoch 13/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 209.4665 - val_loss: 208.3717
Epoch 14/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 207.7745 - val_loss: 206.7824
Epoch 15/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 206.9585 - val_loss: 207.3779
Epoch 16/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 210.5641 - val_loss: 207.8218
Epoch 17/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 209.7144 - val_loss: 207.7526
Epoch 18/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 209.8049 - val_loss: 207.5403
Epoch 19/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 209.3112 - val_loss: 208.1453
Epoch 20/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 204.9464 - val_loss: 208.2735
Epoch 21/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 208.3023 - val_loss: 207.8911
Epoch 22/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 207.6803 - val_loss: 208.5889
Epoch 23/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 208.7152 - val_loss: 208.6871
Epoch 24/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 204.0126 - val_loss: 209.0934
Epoch 25/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 208.1390 - val_loss: 209.1602
Epoch 26/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 203.5447 - val_loss: 210.1361
Epoch 27/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 211.5217 - val_loss: 209.5518
Epoch 28/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 207.9859 - val_loss: 209.4081
Epoch 29/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 204.2299 - val_loss: 209.7379
Epoch 30/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 208.0904 - val_loss: 210.0621

In [53]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(units = 1))

model.compile(optimizer = 'rmsprop',
              loss = 'mae',
              metrics = ['mse'])

model.fit(data, labels, epochs = 30, batch_size = 32, validation_split = 0.2)

Epoch 1/30

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 16.1311 - mse: 388.8939 - val_loss: 12.3898 - val_mse: 206.6732
Epoch 2/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.5349 - mse: 210.8210 - val_loss: 12.3841 - val_mse: 206.4399
Epoch 3/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4085 - mse: 207.7650 - val_loss: 12.3938 - val_mse: 208.5212
Epoch 4/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.6407 - mse: 212.5505 - val_loss: 12.3591 - val_mse: 205.8211
Epoch 5/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4801 - mse: 209.0178 - val_loss: 12.5357 - val_mse: 213.6002
Epoch 6/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.5588 - mse: 211.3399 - val_loss: 12.3988 - val_mse: 207.5105
Epoch 7/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4777 - mse: 208.7207 - val_loss: 12.3632 - val_mse: 206.7739
Epoch 8/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.5120 - mse: 210.3846 - val_loss: 12.4388 - val_mse: 209.3456
Epoch 9/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.5748 - mse: 211.5705 - val_loss: 12.4014 - val_mse: 207.9836
Epoch 10/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.3050 - mse: 205.1749 - val_loss: 12.4760 - val_mse: 211.1970
Epoch 11/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.6300 - mse: 213.1284 - val_loss: 12.4328 - val_mse: 209.5601
Epoch 12/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4628 - mse: 209.7392 - val_loss: 12.4560 - val_mse: 210.6567
Epoch 13/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4132 - mse: 208.1787 - val_loss: 12.4068 - val_mse: 208.6498
Epoch 14/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4796 - mse: 211.2093 - val_loss: 12.4262 - val_mse: 209.6020
Epoch 15/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.3980 - mse: 208.3161 - val_loss: 12.4772 - val_mse: 211.7793
Epoch 16/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4325 - mse: 209.6178 - val_loss: 12.4878 - val_mse: 212.3330
Epoch 17/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 12.4877 - mse: 211.0746 - val_loss: 12.4487 - val_mse: 210.9528
Epoch 18/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 12.4603 - mse: 211.4267 - val_loss: 12.5028 - val_mse: 213.2326
Epoch 19/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 12.5300 - mse: 211.7082 - val_loss: 12.4951 - val_mse: 213.5190
Epoch 20/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4739 - mse: 211.0671 - val_loss: 12.4757 - val_mse: 212.2088
Epoch 21/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.2537 - mse: 206.0484 - val_loss: 12.4646 - val_mse: 211.7663
Epoch 22/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.2878 - mse: 206.5830 - val_loss: 12.5137 - val_mse: 214.1128
Epoch 23/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4388 - mse: 211.0820 - val_loss: 12.6152 - val_mse: 218.3170
Epoch 24/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4109 - mse: 209.4694 - val_loss: 12.4948 - val_mse: 213.5280
Epoch 25/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.3016 - mse: 206.9475 - val_loss: 12.5761 - val_mse: 216.5680
Epoch 26/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4354 - mse: 211.4829 - val_loss: 12.5164 - val_mse: 214.1138
Epoch 27/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.3150 - mse: 208.3674 - val_loss: 12.5453 - val_mse: 215.8353
Epoch 28/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.1983 - mse: 203.6146 - val_loss: 12.5370 - val_mse: 215.4846
Epoch 29/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.1793 - mse: 204.9364 - val_loss: 12.5653 - val_mse: 216.3539
Epoch 30/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.1147 - mse: 204.3584 - val_loss: 12.5245 - val_mse: 214.7405